apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    gcpsm:
      projectID: carbon-zone-496411-s6
      auth:
        workloadIdentity:
          clusterLocation: europe-west3-a
          clusterName: platform
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
