apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-iam
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  package: xpkg.upbound.io/upbound/provider-gcp-iam:v2.5.0
  runtimeConfigRef:
    name: gcp-workload-identity
