apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  projectID: carbon-zone-496411-s6
  credentials:
    source: InjectedIdentity
