apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  ignoreDifferences:
    - group: ""
      kind: Service
      name: crossplane-webhooks
      namespace: crossplane-system
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
        - /spec/ipFamilies
        - /spec/ipFamilyPolicy
        - /spec/internalTrafficPolicy
        - /spec/sessionAffinity
        - /spec/type
  sources:
    - repoURL: https://charts.crossplane.io/stable
      chart: crossplane
      targetRevision: 2.3.1
      helm:
        releaseName: crossplane
        valueFiles:
          - $values/components/crossplane/values.yaml
    - repoURL: https://github.com/inen-pt-group-e/inenp-pt-dmp-platform-gitops
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
