apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  source:
    repoURL: https://github.com/inen-pt-group-e/inenp-pt-dmp-platform-gitops
    targetRevision: main
    path: components/crossplane/config
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 30
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 10m
