apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 2.6.0
      helm:
        releaseName: external-secrets
        valueFiles:
          - $values/components/external-secrets/values.yaml
    - repoURL: https://github.com/inen-pt-group-e/inenp-pt-dmp-platform-gitops
      targetRevision: main
      ref: values
    - repoURL: https://github.com/inen-pt-group-e/inenp-pt-dmp-platform-gitops
      targetRevision: main
      path: components/external-secrets/manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
