apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: tenants.platform.mcce-project.xyz
spec:
  scope: Cluster
  group: platform.mcce-project.xyz
  names:
    kind: Tenant
    plural: tenants
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                database:
                  type: object
                  default: {}
                  properties:
                    instances:
                      type: integer
                      default: 1
                    storageSize:
                      type: string
                      default: "1Gi"
                resources:
                  type: object
                  default: {}
                  properties:
                    requestsCpu:
                      type: string
                      default: "1"
                    requestsMemory:
                      type: string
                      default: "2Gi"
                    limitsCpu:
                      type: string
                      default: "4"
                    limitsMemory:
                      type: string
                      default: "4Gi"
                app:
                  type: object
                  default: {}
                  properties:
                    backendTag:
                      type: string
                      default: "v1.4.0"
                    frontendTag:
                      type: string
                      default: "v1.3.0"
